server.port=8081
spring.application.name=ms-medicos

# 🔐 Validación de Tokens Microsoft Entra ID
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/12d06913-6cce-486f-a7a4-d6202dc5bf6a/v2.0

# ☁️ Base de Datos AWS RDS (MySQL)
spring.datasource.url=jdbc:mysql://${DB_HOST:medictime-db.csqgvtvipjuf.us-east-1.rds.amazonaws.com}:3306/${DB_NAME:medictime}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD}

# 🛠️ JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 📝 Logs de depuración
logging.level.com.medictime.medicos=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# ⚠️ Manejo de errores HTTP
server.error.whitelabel.enabled=false
server.error.include-message=always