server.port=8081
spring.application.name=ms-medicos

# Perfil activo por defecto
spring.profiles.active=dev

# 🔐 Validación de Tokens Microsoft Entra ID
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/12d06913-6cce-486f-a7a4-d6202dc5bf6a/v2.0

# Logs de depuración
logging.level.com.medictime.medicos=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# Manejo de errores HTTP
server.error.whitelabel.enabled=false
server.error.include-message=always